openapi: "3.0.0"
info:
  version: 1.0.0
  title: Open Data Center Service
  contact:
    name: Ken Suenobu
    url: https://www.google.com/
    email: ksuenobu@fastmail.com
  description: None
  license:
    name: Apache License 2.0
servers:
  - url: http://localhost:8080
tags:
  - name: Owners
    description: Handles the manipulation of Data Center owner objects.  Owners are entities to which `Rack`s are associated.
paths:
  /:
    get:
      description: None
      tags:
        - Owners
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
components:
  schemas:
    Owner:
      $ref: './dto/Owner.yml'
    Rack:
      $ref: './dto/Rack.yml'
    RackEquipment:
      $ref: './dto/RackEquipment.yml'
    RackEquipmentService:
      $ref: './dto/RackEquipmentService.yml'
